categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
calendar: Calendar
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: Archives: %s
page: Page %d
recent_posts: Recent Posts
links: Links
about_me: ABOUT ME
duoshuo_recent_comments: Recent Comments
